version: 2
jobs:
  # checks out the code and caches dependencies after acquiring them
  tests:
    docker:
      - image: cypress/base:8
        environment:
          # Enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run:
          name: Running npm ci
          command: npm ci
      # save the cache as the package checksum for future checkout and builds
      - save_cache:
          name: Caching node modules
          key: v1-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Running end-2-end tests
          command: npm run test:ci
          environment:
            TZ: Europe/London
workflows:
  version: 2
  build_test:
    jobs:
      - tests
