
/**
 * Web request model to create a custom report
 * @export
 * @interface CustomReportCreateWebRequestModel
 */
export interface CustomReportCreateWebRequestModel {
  /**
   * The name of the custom report
   * @type {string}
   * @memberof CustomReportCreateWebRequestModel
   */
  name: string;
  /**
   * The Guc of the dodi this report applies to. This report controls will then work in the context of this dodi. If this is an item level report, it can only be generated by items within that dodi
   * @type {string}
   * @memberof CustomReportCreateWebRequestModel
   */
  appliesTo: string;
}
